"""update9

Revision ID: 15347cfef303
Revises: 6b5c39a48172
Create Date: 2024-07-29 16:53:38.124914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15347cfef303'
down_revision: Union[str, None] = '6b5c39a48172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'actions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'is_regular'::character varying"))
    op.drop_constraint('roles_role_name_key', 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('roles_role_name_key', 'roles', ['role_name'])
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'is_regular'::character varying"))
    op.alter_column('permissions', 'actions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
