"""update8

Revision ID: 6b5c39a48172
Revises: c3c9f53010b7
Create Date: 2024-07-29 15:23:09.225264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5c39a48172'
down_revision: Union[str, None] = 'c3c9f53010b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('actions', sa.String(), nullable=True))
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_unique_constraint(None, 'permissions', ['actions'])
    op.drop_column('permissions', 'name')
    op.add_column('roles', sa.Column('role_name', sa.String(), server_default='is_regular', nullable=True))
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['role_name'])
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_column('roles', 'role_name')
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'permissions', type_='unique')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.drop_column('permissions', 'actions')
    # ### end Alembic commands ###
