"""update

Revision ID: 70796a3447aa
Revises: af675c032e39
Create Date: 2024-07-29 06:20:08.544115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70796a3447aa'
down_revision: Union[str, None] = 'af675c032e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_task_fk', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'male'::character varying"))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'male'::character varying"))
    op.add_column('tasks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_task_fk', 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
