"""update10

Revision ID: 72216553afbb
Revises: 8b5d922a6c77
Create Date: 2024-07-29 18:51:57.543524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72216553afbb'
down_revision: Union[str, None] = '8b5d922a6c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'is_regular'::character varying"))
    op.create_unique_constraint(None, 'roles', ['role_name'])
    op.drop_constraint('roles_user_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('roles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('roles_user_id_fkey', 'roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'is_regular'::character varying"))
    # ### end Alembic commands ###
